### ISSUE TITLE
Exception Raised

### ISSUE THREAD

**Issue by ekjswim** [CarstenAgerskov/skill-the-cows-lists#11]
This was a Mycroft Mark I running 18.08.0b. Tried installing the skill a couple times and was told Mycroft couldn't find the skill multiple times until it told me the skill was already installed.
The account already has CowsList on another device, tried authenticating and getting a token with no success. Tried adding a few items to no avail, then got this:

Utterance: add a harmonica to my shopping list

Error in add task to list intent: Traceback (most recent call last): File "/opt/mycroft/skills/carstena-the-cows-lists.carstenagerskov/__init__.py", line 678, in add_task_to_list_intent k, m = self.regex_evaluation_explain(message, ['AddTaskToList']) File "/opt/mycroft/skills/carstena-the-cows-lists.carstenagerskov/__init__.py", line 481, in regex_evaluation_explain for r in self.local_regex[k]: KeyError: 'AddTaskToList'

**Comment by CarstenAgerskov** [comment]
Thanks for reporting this.

Looking at the error, I suspect something went wrong with the installation. If you are familiar with Linux, could you please check that the file /opt/mycroft/skills/carstena-the-cows-lists/regex/en-us/LocalRegex.json exist? You may even check that it contains a key 'AddTaskToList' as the second data entry. 

The file above is part of the install, and it must be readable by the skill. 

I will look into the problem further during the weekend. 

Regards Carsten

**Comment by CarstenAgerskov** [comment]
Also, is your language set to en-us?

Regards Carsten

**Comment by ekjswim** [comment]
Yes, language should be en-us.

Got to the file but not sure what exactly to look for so I'll copy:
```{
  "AddTask": ["add (?P<taskName>.+)"],
  "AddTaskToList": [
    "add (?P<taskName>.+) to (my|the) (?P<listName>.+) list$",
    "add (?P<taskName>.+) to list (?P<listName>.+)$"],
  "FindTask": ["find (?P<taskName>.+)"],
  "FindTaskOnList": [
    "find (?P<taskName>.+) on (my|the) (?P<listName>.+) list$",
    "find (?P<taskName>.+) on list (?P<listName>.+)$"],
  "CompleteTask": ["complete (?!(all))(?P<taskName>.+)"],
  "CompleteTaskOnList": [
    "complete (?P<taskName>.+) on (my|the) (?P<listName>.+) list$",
    "complete (?P<taskName>.+) on list (?P<listName>.+)$"],
  "CompleteList" : [
    "complete all (task(s)?|item(s)?) on (my|the) (?P<listName>.+) list$",
    "complete all (task(s)?|item(s)?) on list (?P<listName>.+)$"],
  "CompleteAll": ["complete all task(s)?"],
  "CompleteTaskInContext": ["complete (it|task)$"],
  "ReadList": ["read (my|the) (?P<listName>.+) list$",
               "read list (?P<listName>.+)$"],
  "Read": ["read( it| the list| my list)?$"],
  "DueOnList" : ["(what is|what's) on (my|the) (?P<listName>.+) list (?P<dueDate>.+)$"],
  "Due" : ["(what is|what's) due (?P<dueDate>.+)$"]
}```

**Comment by ekjswim** [comment]
So the file exists at the location and seems to have the `"AddTaskToList"` bit too.

**Comment by CarstenAgerskov** [comment]
Thanks for finding out about the file and language.

Ok, so the file LocalRegex.json exists, and the skill knows where to find it.
However, the error indicates that the file was not loaded at startup (initial load of the skill). 

You know your way around Linux, but please bear with me when I go into details whe describing commands in the following text. I will only assume knowledge og making an ssh connection to the mycroft server, that way I can reuse or refer to this text later in other cases.

We could examine if there is a collision with multiple installs. Due to changing naming conventions for skills over time, the installation directory may be called:
* carstena-the-cows-lists.carstenagerskov
* carstena-the-cows-lists
* skill-the-cows-lists

Or even something else, in case of a manual install.
Make an ssh connection to the mycroft server, the execute: 
```ls /opt/mycroft/skills/```
If you see more than one of the three installation directories mentioned above, something is wrong.

The best way to fix this is to remove all the-cows-lists directories, restart mycroft, and install again (in that order).
To remove, for instance, the directory skill-the-cows-lists, do a:
```
cd /opt/mycroft/skills/
rm -rf skill-the-cows-lists
```

To restart (stop and start) Mycroft on Linux, see: https://mycroft.ai/documentation/linux/#running-mycroft-for-linux 


If there is only one installation, or the probleme persists, we need to find out what happens when the skill loads. If the usual logs are unusable, try the following.
Open a ssh connection to Mycroft, and start the Mycroft CLI.

To start the CLI on Linux, see: https://mycroft.ai/documentation/linux/#running-mycroft-for-linux

I assume the installaion directory of the skill is carstena-the-cows-lists.carstenagerskov, which is the current naming convention.
Then open another ssh connection to Mycroft, and execute:
```
touch /opt/mycroft/skills/carstena-the-cows-lists.carstenagerskov/__init__.py
```

That will force a skill reload. Within a few secouds the CLI on the other ssh connection should show a line containing the text "...INFO - ATTEMPTING TO LOAD SKILL: carstena-the-cows-lists.carstenagerskov....". Starting from that line and the next 10 or 20 seconds of the cli will be the interesting part, loggong what happens during skill load.
It is possible to navigate the CLI by using the arrow keys.
Resize the CLI terminal to as large as possible, and screenshot or copy the relevant part.

**Comment by CarstenAgerskov** [comment]
I think the immediate bug was fixed, and automatic testing was passed. I am still in the process of manuel testing, to see if anything else is amiss.
A new branch with the changes was created: 18.8.1
If you originally installed using git clone, just do the following in the skill directory:

git pull
git checkout origin/18.8.1

Otherwise you may read the 'Installation' section in the README.md in https://github.com/CarstenAgerskov/skill-the-cows-lists/tree/18.8.1

Regards Carsten
