### ISSUE TITLE
Error while loading skill - no module urllib2

### ISSUE THREAD

**Issue by dvpfig** [CarstenAgerskov/skill-the-cows-lists#12]
Hi, 

I am trying to test this skill on mycroft but was not able so far. I have added the api and secret in the .mycroft/mycroft.conf file. 

While loading the skill the text below shows an error of missing lib: 

----------------------------------------------------------------------------
15:49:51.896 - mycroft.skills.core:load_skill:107 - INFO - ATTEMPTING TO LOAD SKILL: skill-the-cows-lists.carstenagerskov with ID skill-the-cows-lists.carstenagerskov
15:49:52.025 - mycroft.skills.core:load_skill:151 - ERROR - Failed to load skill: skill-the-cows-lists.carstenagerskov
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 117, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.5/imp.py", line 172, in load_source
module = _load(spec)
File "<frozen importlib._bootstrap>", line 693, in _load
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 673, in exec_module
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "/opt/mycroft/skills/skill-the-cows-lists.carstenagerskov/__init__.py", line 34, in <module>
import cow_rest
File "/opt/mycroft/skills/skill-the-cows-lists.carstenagerskov/cow_rest.py", line 20, in <module>
from urllib2 import urlopen
ImportError: No module named 'urllib2'
----------------------------------------------------------------------------

**Comment by CarstenAgerskov** [comment]
It seems you have pulled the master branch from GitHub, is that right?
If so, please try the 18.2.6b branch instead, which is for python3 versions of Mycroft: https://github.com/CarstenAgerskov/skill-the-cows-lists/tree/18.2.6b

Let me know if it works for you.

Regards Carsten

**Comment by dvpfig** [comment]
Hi, 

I have tried the branch 18.2.6b, it went a few steps further, but still no luck. I am now using this branch. 
I see now the configuration window in the home.mycroft.ai skills section where I placed the API and secret, i.e. no need anymore to use the manual mycroft.conf (removed the lines for cowslist from there). 

However, the skill is still not loading correctly: 

------------
21:32:03.241 - mycroft.skills.core:load_skill:107 - INFO - ATTEMPTING TO LOAD SKILL: skill-the-cows-lists.carstenagerskov with ID skill-the-cows-lists.carstenagerskov
21:32:06.173 - mycroft.skills.settings:_send_settings_meta:218 - ERROR - [{'key': 'skill.schema.invalid'}]
21:32:07.059 - mycroft.skills.settings:_send_settings_meta:218 - ERROR - [{'key': 'skill.schema.invalid'}]
21:32:07.132 - mycroft.skills.core:load_skill:151 - ERROR - Failed to load skill: skill-the-cows-lists.carstenagerskov
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 135, in load_skill
raise e
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 131, in load_skill
skill.initialize()
File "/opt/mycroft/skills/skill-the-cows-lists.carstenagerskov/__init__.py", line 74, in initialize
self.no_keyword = open(self.vocab_dir + '/NoKeyword.voc', 'r').read()
AttributeError: 'CowsLists' object has no attribute 'vocab_dir'


/Daniel

**Comment by dvpfig** [comment]
Btw, I'm on mycroft version 18.8.1. 

/Daniel

**Comment by CarstenAgerskov** [comment]
The immediate bug was fixed, and automatic testing was passed. I am still in the process of manuel testing, to see if anything else is amiss.
A new branch with the changes was created: 18.8.1
If you originally installed using git clone, just do the following in the skill directory:
```
git pull
git checkout origin/18.8.1
```
Otherwise you may read the 'Installation' section in the README.md in https://github.com/CarstenAgerskov/skill-the-cows-lists/tree/18.8.1

Regards Carsten
