### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by wjjessen** [CarstenAgerskov/skill-the-cows-lists#8]
Hey Mycroft, authenticate with Remember the Milk.
>> Error in get token intent at line 556. Do you want me to send a mail with the last exception, to help you report the issue?
>>
Yes.
>> Sorry, I don't understand.
>>
From mycroft-skills.log:
23:07:44.693 - SKILLS - DEBUG - {"data": {"name": "TheCowsLists.authenticate_intent"}, "type": "mycroft.skill.handler.start", "context": null}
23:07:44.896 - skill-the-cows-lists__init__ - ERROR - Error in get token intent: Traceback (most recent call last):
  File "/opt/mycroft/skills/skill-the-cows-lists/__init__.py", line 556, in authenticate_intent
    error_text, error_code = cow_rest.get_frob(cow_rest)
  File "/opt/mycroft/skills/skill-the-cows-lists/cow_rest.py", line 185, in get_frob
    response = r.call()
  File "/opt/mycroft/skills/skill-the-cows-lists/cow_rest.py", line 57, in call
    s = urlopen(RTM_URL + self.get_param_string())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 526: Origin SSL Certificate Error
Traceback (most recent call last):
  File "/opt/mycroft/skills/skill-the-cows-lists/__init__.py", line 556, in authenticate_intent
    error_text, error_code = cow_rest.get_frob(cow_rest)
  File "/opt/mycroft/skills/skill-the-cows-lists/cow_rest.py", line 185, in get_frob
    response = r.call()
  File "/opt/mycroft/skills/skill-the-cows-lists/cow_rest.py", line 57, in call
    s = urlopen(RTM_URL + self.get_param_string())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 526: Origin SSL Certificate Error
23:07:44.910 - SKILLS - DEBUG - {"data": {"expect_response": false, "utterance": "Error in get token intent at line 556"}, "type": "speak", "context": {"client_name": "mycroft_listener", "ident": "1524366462.92-1850353301", "target": null}}

**Comment by CarstenAgerskov** [comment]
Thank you for reporting this problem.
I will look int it, but until then, please recheck your secret and API key: A mistake in either of them may result in an error like this. If you change the API key or secret, please restart Mycroft to be sure the skill looks at the new values.
Are you on Linux or pi?

Regards Carsten

**Comment by CarstenAgerskov** [comment]
Hi

I am sorry, I am not able to recreate the problem. 

From the log I strongly suspect that the problem is with Remember the Milk, and that it is temporary.

Reasoning: The error "HTTPError: HTTP Error 526: Origin SSL Certificate Error" is a HTTP status code you will only find in the CloudFlare software. Remember the milk use CloudFlare as reverse proxy. My guess is that CloudFlare hits a RTM server with an expired, or otherwise illegal, certificate. 

Regards Carsten

**Comment by wjjessen** [comment]
I'm on a pi. And you are right -- it was a temporary problem. I tried again tonight and it worked the first time!
