### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by adamc199** [CarstenAgerskov/skill-the-cows-lists#9]
My mark1 rebooted last night and this skill broke.
I reset my device completely, but now cannot install the skill due to a pip error:
 msm install https://github.com/CarstenAgerskov/skill-the-cows-lists
INFO - Downloading skill: https://github.com/CarstenAgerskov/skill-the-cows-lists
INFO - Installing requirements.txt for skill-the-cows-lists
PipRequirementsException:
Pip returned code 1:

Exception:
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/commands/install.py", line 241, in run
    with self._build_session(options) as session:
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 101, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/__init__.py", line 246, in main
    return command.main(cmd_args)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 264, in main
    timeout=min(5, options.timeout)) as session:
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 101, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1

Yet pip is installed and works from the command line

**Comment by adamc199** [comment]
It appears the 'upgrade" to python3.x broke a lot of skills, including this one :-(

**Comment by CarstenAgerskov** [comment]
And if you try the instructions, just to be clear: You want the 18.2.6b branch for Python3.
Good luck, and don't hesitate to ask if the installation cause trouble

**Comment by adamc199** [comment]
Thanks! Plowing through it all now :-)

**Comment by adamc199** [comment]
It Worked!

Thank you for the help and the great work on this skill. It's appreciated!

**Comment by CarstenAgerskov** [comment]
I hope it is OK to reference this issue in the MycroftAI/mycroft-skills repo. Thanks in advance. Otherwise let me know.

Regards Carsten

**Comment by CarstenAgerskov** [comment]
Actually, I will not make the reference, your feedback is valued, and I will not use it for something other that what was intended by you. I have removed the reference.
 
Regards Carsten
